## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [138]:
import numpy as np

np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [11]:
n = 2

np.array([1, 2, 3]*n)

array([1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [13]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [48]:
arr = np.zeros((10, 10))

arr[0, :], arr[:, 0], arr[:, 9], arr[9, :] = [1, 1, 1, 1]
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [46]:
arr = np.zeros((8, 8))

arr[0::2, 1::2], arr[1::2, 0::2] = [1, 1]
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [68]:
def ij_sum_matrix(n):
    arr1 = np.zeros((n, n))
    arr2 = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            arr1[j, i], arr2[i, j] = [i, i]
    return arr1 + arr2

ij_sum_matrix(10)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [121]:
vec1 = np.array([1, 2, 3, 4])
vec2 = np.array([[1], [2], [3], [4]])
matrix1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
matrix2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

print(np.dot(vec1, vec2), 'is the product of two vectors\n')
print(np.dot(matrix1, vec2), 'is the product of a matrix and a vector\n')
print(np.dot(matrix1, matrix2), 'is the product of two matrices')



[30] is the product of two vectors

[[30]
 [70]] is the product of a matrix and a vector

[[ 50  60]
 [114 140]] is the product of two matrices


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [127]:
steps = 1/0.05

cosines = np.cos(np.linspace(0, 1, int(steps)))
sines = np.sin(np.linspace(0, 1, int(steps)))

print(list(cosines)+list(sines))

[1.0, 0.9986152781425827, 0.9944649474795756, 0.9875605021181478, 0.9779210635311101, 0.9655733276010717, 0.9505514906876966, 0.9328971549228098, 0.912659212995635, 0.8898937127472434, 0.8646637019492132, 0.8370390536963741, 0.8070962728972044, 0.7749182843977933, 0.7405942033261461, 0.7042190882928544, 0.6658936781316236, 0.625724112908743, 0.5838216399741468, 0.5403023058681397, 0.0, 0.05260728333807213, 0.10506887376594912, 0.15723948186175024, 0.20897462406278547, 0.2601310228046501, 0.3105670033203749, 0.3601428860007191, 0.40872137322898616, 0.4561679296190457, 0.5023511546035125, 0.547143146340223, 0.5904198559291864, 0.6320614309590333, 0.6719525474315213, 0.709982729144858, 0.7460466536513234, 0.7800444439418607, 0.8118819450498316, 0.8414709848078965]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [285]:
a = np.random.rand(3,5)
a

array([[0.84865525, 0.96902941, 0.71352227, 0.26889308, 0.24546076],
       [0.18241813, 0.88335877, 0.87292869, 0.31765535, 0.79606681],
       [0.03456426, 0.07581968, 0.48718099, 0.61311692, 0.27688411]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [292]:
sum = np.sum(a)
sum_col = np.sum(a, axis = 0)
sum_row = np.sum(a, axis = 1)
mean = np.mean(a, axis = 1)
variance = np.var(a, axis = 1)
std_deviation = np.std(a, axis = 1)
print(f'Сумма всех элементов: {sum}\nCумма внутри строк: {sum_row}\nСумма внутри столбцов: {sum_col}\n' \
      f'Средние значения: {mean}\nДисперсии: {variance}\nСтандартные отклонения: {std_deviation}')


Сумма всех элементов: -3.191891195797325e-16
Cумма внутри строк: [-1.33226763e-15  7.77156117e-16  5.68989300e-16]
Сумма внутри столбцов: [-1.79579643  1.1351703   2.06865901 -0.7195484  -0.68848447]
Средние значения: [-2.66453526e-16  1.55431223e-16  1.13797860e-16]
Дисперсии: [1. 1. 1.]
Стандартные отклонения: [1. 1. 1.]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [293]:
for i in range(len(a)):
    a[i, :] = (a[i, :] - np.mean(a[i])) / np.std(a[i])
a

array([[ 0.80221675,  1.20534327,  0.3496638 , -1.13937511, -1.2178487 ],
       [-1.43204354,  0.91286168,  0.87796918, -0.97962513,  0.62083782],
       [-1.16596965, -0.98303465,  0.84102603,  1.39945184, -0.09147359]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [294]:
col = a[:, 3]
sorted = np.argsort(a[:, 3])
temp = np.zeros((3,))
for i in range(3):
    temp[i] = col[sorted[i]]
a[:, 3] = temp
a

array([[ 0.80221675,  1.20534327,  0.3496638 , -1.13937511, -1.2178487 ],
       [-1.43204354,  0.91286168,  0.87796918, -0.97962513,  0.62083782],
       [-1.16596965, -0.98303465,  0.84102603,  1.39945184, -0.09147359]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [303]:
b = np.dot(np.transpose(a), a)
c = np.dot(a, np.transpose(a))

print(f'Матрица B: {b}\n\nМатрица C: {c}')

"""
Матрицы B и C схожи числом измерений 2 и типом данных значений - float64.
Отличаются они хранящимися в них значениями, размерами (у А размер - (5,5), у B - (3,3)) 
и количествами элементов (25 и 9 соответсвенно).
"""

Матрица B: [[ 4.05378563  0.80587746 -1.95739475 -1.14287834 -1.75939   ]
 [ 0.80587746  3.25252594  0.39617159 -3.64331001 -0.81126498]
 [-1.95739475  0.39617159  1.60041943 -0.08150347  0.0423072 ]
 [-1.14287834 -3.64331001 -0.08150347  4.21630651  0.6513853 ]
 [-1.75939    -0.81126498  0.0423072   0.6513853   1.87696248]]

Матрица C: [[ 5.          0.61857035 -3.30927784]
 [ 0.61857035  5.          0.08301112]
 [-3.30927784  0.08301112  5.        ]]


'\nМатрицы B и C схожи числом измерений 2 и типом данных значений - float64.\nОтличаются они хранящимися в них значениями, размерами (у А размер - (5,5), у B - (3,3)) \nи количествами элементов (25 и 9 соответсвенно).\n'

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [296]:
np.sum(np.diagonal(b)) + np.sum(np.diagonal(c))

30.0

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [301]:
#det_a = np.linalg.det(a) - найти нельзя, потому что матрица A - не квадратная.
det_b = np.linalg.det(b)
det_c = np.linalg.det(c)
rank_a = np.linalg.matrix_rank(a)
rank_b = np.linalg.matrix_rank(b)
rank_c = np.linalg.matrix_rank(c)
w_b, v_b = np.linalg.eig(b)
w_c, v_b = np.linalg.eig(c)

print(f'Ранг матрицы А: {rank_a}\nДетерминант матрицы B: {det_b}\nРанг матрицы B: {rank_b}\n' \
      f'Спектр матрицы B: {w_b}\nДетерминант матрицы C: {det_c}\nРанг матрицы C: {rank_c}\n' \
      f'Спектр матрицы C: {w_c}\n')

"""
У матриц A, B, C ранг одинковый. Из этого можно сделать вывод, что при умножении матрицы в любом порядке 
на себя транспонированную ранг не меняется. Но меняется детерминант и собственные значения.
"""

Ранг матрицы А: 3
Детерминант матрицы B: -2.9871593360491497e-30
Ранг матрицы B: 3
Спектр матрицы B: [8.35253165e+00 5.02996938e+00 1.61749897e+00 7.39728671e-16
 1.50032335e-16]
Детерминант матрицы C: 67.95594926484566
Ранг матрицы C: 3
Спектр матрицы C: [1.61749897 8.35253165 5.02996938]



'\nУ матриц A, B, C ранг одинковый. Поэтому можно сделать вывод, что при умножении матрицы влюбом порядке \nна себя транспонированную ранг не меняется. Также могут появиться собственные значения.\n'

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>